/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Controle.Vendedor;
import Controle.Departamento;
import Controle.RegistroVendas;
import DAO.VendedorDao;
import DAO.DepartamentoDao;
import DAO.RegistroVendasDao;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 04795661197
 */
public class FormRegistroVenda extends javax.swing.JFrame {
        Vector<Vendedor> vendedor;
        Vector<Departamento> depart;

    /**
     * Creates new form FormCliente
     */
    public FormRegistroVenda() {
        initComponents();
        CarregarTabela();
        bloquear();
        RegistroVendasDao registroDao = new RegistroVendasDao();
        vendedor = registroDao.CarregarVendedor();
        combVendedor.setModel(new DefaultComboBoxModel(vendedor));

        depart = registroDao.CarregarDepartamento();
        combDepart.setModel(new DefaultComboBoxModel(depart));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtComissao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalVendas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPComisao = new javax.swing.JTextField();
        combVendedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combDepart = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRegistroV = new javax.swing.JTable();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("S. Comissão");

        jLabel3.setText("Total de Vendas");

        jLabel4.setText("Data Venda");

        jLabel5.setText("P. Comissão");

        txtPComisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPComisaoActionPerformed(evt);
            }
        });

        combVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Vendedor");

        jLabel7.setText("Departamento");

        combDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbRegistroV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "S. Comissão", "Total Vendas", "Data Venda", "P. Comissão", "Vendedor", "Departamento"
            }
        ));
        tbRegistroV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRegistroVMouseClicked(evt);
            }
        });
        tbRegistroV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRegistroVKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbRegistroV);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtPComisao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(combVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btNovo)
                            .addGap(49, 49, 49)
                            .addComponent(btSalvar)
                            .addGap(60, 60, 60)
                            .addComponent(btExcluir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btEditar)
                            .addGap(46, 46, 46)
                            .addComponent(btCancelar)
                            .addGap(33, 33, 33)
                            .addComponent(btSair))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPComisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btEditar)
                    .addComponent(btCancelar)
                    .addComponent(btSair))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPComisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPComisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPComisaoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (txtCod.getText().equals("")) {
            int i = JOptionPane.showConfirmDialog(null, "Deseja Salvar os Dados", "Cadastro de Registro Vendas", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
                SalvarRegistroVendas();
                CarregarTabela();
                bloquear();
            } 
        }else {
            int i = JOptionPane.showConfirmDialog(null, "Deseja Atualizar os Dados", "Cadastro de Registro Vendas", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
                AtualizarRegistroVendas();
                CarregarTabela();
                bloquear();
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Deseja Excluir os Dados", "Cadastro de Registro Vendas", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_NO_OPTION) {
                ExcluirRegistroVendas();
                CarregarTabela();
            }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void tbRegistroVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRegistroVMouseClicked
           preencherjTextCombox();




    // TODO add your handling code here:
    }//GEN-LAST:event_tbRegistroVMouseClicked

    private void tbRegistroVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRegistroVKeyPressed
        preencherjTextCombox();



    // TODO add your handling code here:
    }//GEN-LAST:event_tbRegistroVKeyPressed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        desbloquear();
        txtCod.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        desbloquear();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        bloquear();

        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistroVenda().setVisible(true);
            }
        });
    }
    
    //Método salvar 

    public boolean SalvarRegistroVendas() {

        RegistroVendas resgistro = new RegistroVendas();
        
        resgistro.setStatusComissao(Double.parseDouble(txtComissao.getText()));
        resgistro.setTotalVenda(Double.parseDouble(txtTotalVendas.getText()));
        resgistro.setDataVenda(txtDataVenda.getText());
        resgistro.setPercentComissao(Double.parseDouble(txtPComisao.getText()));
        resgistro.setCodigoVendedor(vendedor.get(combVendedor.getSelectedIndex()));
        resgistro.setCodigoDepartamento(depart.get(combDepart.getSelectedIndex()));
        RegistroVendasDao registroDao = new RegistroVendasDao();
        registroDao.SalvarRegistroVendas(resgistro);

        return true;

    }

    // Método Atualizar 
    public boolean AtualizarRegistroVendas() {

        RegistroVendas registro = new RegistroVendas();

        registro.setCodigoRegistroVendas(Integer.parseInt(txtCod.getText()));
        registro.setStatusComissao(Double.parseDouble(txtComissao.getText()));
        registro.setTotalVenda(Double.parseDouble(txtTotalVendas.getText()));
        registro.setDataVenda(txtDataVenda.getText());
        registro.setPercentComissao(Double.parseDouble(txtPComisao.getText()));
        registro.setCodigoVendedor(vendedor.get(combVendedor.getSelectedIndex()));
        registro.setCodigoDepartamento(depart.get(combDepart.getSelectedIndex()));
        RegistroVendasDao registroDao = new RegistroVendasDao();
        registroDao.AtualizarRegistroVendas(registro);

        return true;

    }
    
    // Método de excluir

    private boolean ExcluirRegistroVendas() {
        // Classe que contém os métodos get e set
        RegistroVendas registro = new RegistroVendas();
        registro.setCodigoRegistroVendas(Integer.parseInt(txtCod.getText()));
        // Classe que contém o método de exclusão 
        RegistroVendasDao dao = new RegistroVendasDao();
        dao.Excluir(registro);

        return true;

    }

    // método Carregar Tabela
    public void CarregarTabela() {

        Vector cabecalho;
        cabecalho = new Vector();
        cabecalho.add("Código");
        cabecalho.add("StatusComissao");
        cabecalho.add("TotalVendas");
        cabecalho.add("DataVenda");
        cabecalho.add("PercentComissao");
        cabecalho.add("Vendedor");
        cabecalho.add("Departamento");

        RegistroVendasDao registroDao = new RegistroVendasDao();
        tbRegistroV.setModel(new DefaultTableModel(registroDao.CarregarRegistroVendasTabela(), cabecalho));
    }
    
    
   
   // método para a devolução de valores
    
    public  boolean preencherjTextCombox (){
        int x = Integer.parseInt(tbRegistroV.getModel().getValueAt(tbRegistroV.getSelectedRow(),0).toString());
        RegistroVendas registro = new RegistroVendas();
         RegistroVendasDao registroDao =new RegistroVendasDao();
         registro=registroDao.PesquisarRegistro(x);
        
        
             
       combVendedor.getModel().setSelectedItem(registro.getCodigoVendedor());
       combDepart.getModel().setSelectedItem(registro.getCodigoDepartamento());
       
        
        txtCod.setText(String.valueOf(registro.getCodigoRegistroVendas()));
        txtComissao.setText(String.valueOf(registro.getStatusComissao()));
        txtTotalVendas.setText(String.valueOf(registro.getTotalVenda()));
        txtDataVenda.setText(String.valueOf(registro.getDataVenda()));
        txtPComisao.setText(String.valueOf(registro.getPercentComissao()));
        
        return  true;
        
    }
    
    public boolean bloquear() {
        txtCod.setEditable(false);
        txtComissao.setEditable(false);
        txtTotalVendas.setEditable(false);
        txtDataVenda.setEditable(false);
        txtPComisao.setEditable(false);
        combVendedor.setEditable(false);
        combDepart.setEditable(false);
        btNovo.setEnabled(true);
        btSalvar.setEnabled(false);
        btExcluir.setEnabled(true);
        btEditar.setEnabled(true);
        btCancelar.setEnabled(false);
        btSair.setEnabled(true);
        return true;
    }
    
    public boolean desbloquear() {
        txtCod.setEditable(false);
        txtComissao.setEditable(true);
        txtTotalVendas.setEditable(true);
        txtDataVenda.setEditable(true);
        txtPComisao.setEditable(true);
        combVendedor.setEditable(true);
        combDepart.setEditable(true);
        btNovo.setEnabled(false);
        btSalvar.setEnabled(true);
        btExcluir.setEnabled(true);
        btEditar.setEnabled(false);
        btCancelar.setEnabled(true);
        btSair.setEnabled(true);
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> combDepart;
    private javax.swing.JComboBox<String> combVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRegistroV;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtComissao;
    private javax.swing.JTextField txtDataVenda;
    private javax.swing.JTextField txtPComisao;
    private javax.swing.JTextField txtTotalVendas;
    // End of variables declaration//GEN-END:variables
}
